// The component receives a list of available images generated by ImagesList-hook.jsx
// along with a basename ("plant", "water").
// It displays a small modal under the clicked image, showing all available options,
// allowing the user to select a new image.

import React from "react";

import Backdrop from "./Backdrop";

import "./LogoPicker.css";

interface LogoItem {
  id: number;
  img: number;
}

interface LogoPickerProps {
  show: boolean;
  onCancel: () => void;
  availableLogos: LogoItem[];
  basename: string;
  selectedLogo: string | null;
  onSelect: (img: number) => void;
}

const LogoPicker: React.FC<LogoPickerProps> = (props) => {
  return (
    <>
      {props.show && <Backdrop onClickProp={props.onCancel} />}
      <div className="logo-picker">
        {props.availableLogos.map((plant) => (
          <div
            key={plant.id}
            className={`logo-option ${
              props.selectedLogo === String(plant.img) ? "selected" : ""
            }`}
            onClick={() => {
              props.onSelect(plant.img);
            }}
          >
            <img
              src={`images/${props.basename}_${plant.img}.svg`}
              alt={`plant_${plant.img}`}
              className="plant-logo"
            />
          </div>
        ))}
      </div>
    </>
  );
};

export default LogoPicker;
